routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix' => 'admin', 'namespace' => 'App\\Http\\Controllers\\Admin', 'middleware' => 'auth'], function() {
    Route::get('/', 'MainController@index')->name('admin.index');
    Route::get('/file-manager', 'FileManagerController@show')->name('admin.file-manager');
    Route::get('/settings', 'Setting\SettingController@edit')->name('admin.settings');
    Route::post('/settings/update/{id}', 'Setting\SettingController@update')->name('settings.update');
    Route::resource('news', 'News\NewsController');
    Route::resource('pages', 'Page\PageController');
    Route::resource('feedbacks', 'Feedback\FeedbackController');
    Route::post('/pages/drag-and-drop', 'Page\PageController@processDragAndDrop')->name('pages.processDragAndDrop');
});

Auth::routes();

resources/views/admin/page/list.blade.php
@extends('admin.layout.table')

@section('title', 'Страницы и меню')

@section('breadcrumbs')
    <li class="breadcrumb-item">Структура сайта</li>
@endsection

@section('create_url')
    {{ route('pages.create') }}
@endsection

@section('table')
    <div id="js-tree" class="p-2" data-move-url="{{ route('pages.processDragAndDrop') }}" data-token="{{ csrf_token() }}" data-tree-key="page">
        <ul role="group">
            @foreach($pages as $item)
                <li role="treeitem" class="jstree-open" aria-level="1" id="{{ $item->id }}">{{ $item->title }}
                    @if($item->children)
                        <ul role="group" class="jstree-children">
                            @foreach($item->children as $cats)
                                <li role="treeitem" aria-level="2" id="{{ $cats->id }}"><a href="{{ route('pages.show', [$cats->id]) }}">{{ $cats->title }}</a>
                                    @if($cats->children)
                                        <ul role="group" class="jstree-children">
                                            @foreach($cats->children as $cat)
                                                <li aria-level="3" id="{{ $cat->id }}"><a href="{{ route('pages.show', [$cat->id]) }}">{{$cat->title}}</a></li>
                                            @endforeach
                                        </ul>
                                    @endif
                                </li>
                            @endforeach
                        </ul>
                    @endif
                </li>
            @endforeach
        </ul>
    </div>
@stop

@section('css')
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jstree/3.3.5/themes/default/style.min.css" />
@stop

@section('js')
    @parent
    <script src="//cdnjs.cloudflare.com/ajax/libs/jstree/3.3.5/jstree.min.js"></script>
    <script src="{{ asset('js/app/js/jstree.js') }}" defer></script>
@stop

resources/views/admin/page/view.blade.php
@extends('admin.layout.form')

@section('title')
    Редактировать страницу
@stop

@section('breadcrumbs')
    <li class="breadcrumb-item"><a href="{{ route('pages.index') }}">Новости</a></li>
    <li class="breadcrumb-item">Создание новости</li>
@endsection

@section('form')
    @if (Session::has('success'))
        <div class="alert alert-success" role="alert">
            {{ Session::get('success') }}
        </div>
    @endif
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form role="form"
          action="@if($page->id){{ route('pages.update', $page->id) }}@else{{ route('pages.store') }}@endif"
          method="POST">
        @if($page->id)
            @method('put')
        @endif
        @csrf
        <div class="card-body">
            <div class="form-group">
                <label for="title">Заголовок</label>
                <input type="text" class="form-control js-transliterate-source" id="title" name="title" placeholder="Заголовок" value="{{ $page->title }}">
            </div>
            <div class="form-group">
                <label for="alias">Алиас</label>
                <a href="#" id="js-transliterate-run" class="float-right" title="Сгенерировать алиас">Сгенерировать</a>
                <input type="text" class="form-control js-transliterate-destination" id="alias" name="alias" placeholder="Алиас" value="{{ $page->alias }}">
            </div>
            <div class="form-group">
                <label for="parent">Родительская страница</label>
                <select class="form-control" name="parent_id">
                    @foreach($pages as $item)
                        @if($page->id !== $item->id)
                            <option value="{{ $item->id }}" @if($page->parent_id === $item->id) selected @endif> {{ $item->title }}</option>
                        @endif
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label for="content">Контент</label>
                <textarea name="content" id="content" class="ckeditor form-control">{{ $page->content }}</textarea>
            </div>

            <div class="form-group">
                <label class="control-label required">Опубликовано</label>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="is_published" value="1" @if($page->is_published === 1) checked @endif>
                    <label class="form-check-label">Да</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="is_published" value="0" @if($page->is_published  === 0) checked @endif>
                    <label class="form-check-label">Нет</label>
                </div>
            </div>
        </div>

        <div class="card-footer">
            <button type="submit" class="btn btn-sm btn-success">Сохранить</button>
            @if($page->id)
                <a href="{{ route('pages.create') }}" type="button" class="btn btn-sm btn-primary">Создать</a>
                <a href="{{ route('pages.destroy', $page->id) }}" type="button" class="btn btn-sm btn-danger float-right">Удалить</a>
            @endif
        </div>
    </form>
    @if($page->id)
        <form class="form" method="POST" action="{{ route('pages.destroy', $page->id) }}">
            @csrf
            @method('DELETE')
            <div class="card-body">
                <button type="submit" class="btn btn-sm btn-danger float-right">Удалить</button>
            </div>
        </form>
    @endif
@stop

@section('css')
    @parent
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker3.min.css">
@stop

@section('js')
    @parent

    <script src="{{ asset('js/app/libs/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('js/app/js/ckeditor.js') }}"></script>
    <script src="{{ asset('js/app/js/elfinder-file-type.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/locales/bootstrap-datepicker.ru.min.js"></script>
    <script src="{{ asset('js/app/js/datapicker.js') }}"></script>
    <script src="{{ asset('js/app/js/transliterate.js') }}"></script>
@stop