routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix' => 'admin', 'namespace' => 'App\\Http\\Controllers\\Admin', 'middleware' => 'auth'], function() {
    Route::get('/', 'MainController@index')->name('admin.index');
    Route::get('/file-manager', 'FileManagerController@show')->name('admin.file-manager');
    Route::get('/settings', 'Setting\SettingController@edit')->name('admin.settings');
    Route::post('/settings/update/{id}', 'Setting\SettingController@update')->name('settings.update');
    Route::resource('news', 'News\NewsController');
    Route::resource('pages', 'Page\PageController');
    Route::resource('feedbacks', 'Feedback\FeedbackController');
    Route::post('/pages/drag-and-drop', 'Page\PageController@processDragAndDrop')->name('pages.processDragAndDrop');
});

Auth::routes();

app/Models/Feedbacks/Feedbacks.php
<?php

namespace App\Models\Feedbacks;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Feedbacks extends Model
{
    use HasFactory;

    protected $table = 'feedbacks';

    protected $fillable = [
        'name',
        'email',
        'phone',
        'question',
    ];
}

app/Http/Controllers/Admin/Feedback/FeedbackController.php
<?php

namespace App\Http\Controllers\Admin\Feedback;

use App\Http\Requests\FeedbackRequest;
use App\Models\Feedbacks\Feedbacks;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class FeedbackController extends Controller
{

    public function index()
    {
        return view('admin.feedback.list', [
            'feedbacks' => Feedbacks::orderBy('created_at','desc')->paginate(10)
        ]);
    }

    public function show($id)
    {
        return view('admin.feedback.view', [
            'feedback' => Feedbacks::find($id)
        ]);
    }

    public function create()
    {
        return view('admin.feedback.view', [
            'feedback' => new Feedbacks()
        ]);
    }

    public function store(FeedbackRequest $request)
    {
        $validation = $request->validated();
        $feedback = Feedbacks::create($validation);

        return redirect('admin/feedbacks/' . $feedback->id)->with('success', 'Обращение успешно сохранен!');
    }

    public function update(FeedbackRequest $request, int $id)
    {
        $validation = $request->validated();
        $feedback = Feedbacks::find($id);
        $feedback->update($validation);

        return redirect('admin/feedbacks/' . $feedback->id)->with('success', 'Обращение успешно изменена!');
    }

    public function destroy(int $id)
    {
        $feedback = Feedbacks::find($id);
        $feedback->delete();

        return redirect('admin/feedbacks')->with('success', 'Обращение удалена');
    }
}

resources/views/admin/feedback/list.blade.php
@extends('admin.layout.table')

@section('title', 'Обратная связь')

@section('breadcrumbs')
    <li class="breadcrumb-item">Обратная связь</li>
@endsection

@section('create_url')
    {{ route('feedbacks.create') }}
@endsection

@section('table')
    <table class="table table-hover table-sm">
        <thead>
        <tr>
            <th>#ID</th>
            <th>ФИО</th>
            <th>Почта</th>
            <th>Телефон</th>
            <th>Дата обращения</th>
        </tr>
        </thead>
        <tbody>
            @foreach ($feedbacks as $item)
                <tr>
                    <td><a href="{{ route('feedbacks.show', [$item->id]) }}">{{ $item->id }}</a></td>
                    <td><a href="{{ route('feedbacks.show', [$item->id]) }}">{{ $item->name }}</a></td>
                    <td>{{ $item->email }}</td>
                    <td>{{ $item->phone }}</td>
                    <td>{{ date('d.m.Y H:m:s', strtotime($item->created_at)) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
    <div class="d-flex justify-content-center">
        {!! $feedbacks->links() !!}
    </div>
@stop

resources/views/admin/feedback/view.blade.php
@extends('admin.layout.form')

@section('title')
    Редактировать обращение
@endsection

@section('breadcrumbs')
    <li class="breadcrumb-item"><a href="{{ route('news.index') }}">Обращения</a></li>
    <li class="breadcrumb-item">Редактирование обращение</li>
@endsection

@section('form')
    @if (Session::has('success'))
        <div class="alert alert-success" role="alert">
            {{ Session::get('success') }}
        </div>
    @endif
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form role="form"
          action="@if($feedback->id){{ route('feedbacks.update', $feedback->id) }}@else{{ route('feedbacks.store') }}@endif"
          method="POST">
            @if($feedback->id)
                @method('put')
            @endif
        @csrf
        <div class="card-body">
            <div class="form-group">
                <label for="name">ФИО</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="ФИО" value="{{ $feedback->name }}">
            </div>
            <div class="form-group">
                <label for="email">Почта</label>
                <input type="text" class="form-control" id="email" name="email" placeholder="Почта" value="{{ $feedback->email }}">
            </div>
            <div class="form-group">
                <label for="phone">Телефон</label>
                <input type="text" class="form-control" id="phone" name="phone" placeholder="Телефон" value="{{ $feedback->phone }}">
            </div>
            <div class="form-group">
                <label for="date">Дата обращения</label>
                <input type="text" class="js-datepicker form-control" id="date" name="date" placeholder="Дата" value="{{ date('d.m.Y H:m:s', strtotime($feedback->created_at)) }}">
            </div>
            <div class="form-group">
                <label for="question">Вопрос</label>
                <textarea name="question" id="question" class="form-control">{{ $feedback->question }}</textarea>
            </div>
        </div>

        <div class="card-footer">
            <button type="submit" class="btn btn-sm btn-success">Сохранить</button>
        </div>
    </form>
    @if($feedback->id)
        <form class="form" method="POST" action="{{ route('feedbacks.destroy', $feedback->id) }}">
            @csrf
            @method('DELETE')
            <div class="card-body">
                <button type="submit" class="btn btn-sm btn-danger float-right">Удалить</button>
            </div>
        </form>
    @endif
@stop

@section('css')
    @parent
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker3.min.css">
@stop

@section('js')
    @parent

    <script src="{{ asset('js/app/libs/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('js/app/js/ckeditor.js') }}"></script>
    <script src="{{ asset('js/app/js/elfinder-file-type.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/locales/bootstrap-datepicker.ru.min.js"></script>
    <script src="{{ asset('js/app/js/datapicker.js') }}"></script>
    <script src="{{ asset('js/app/js/transliterate.js') }}"></script>
@stop