routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix' => 'admin', 'namespace' => 'App\\Http\\Controllers\\Admin', 'middleware' => 'auth'], function() {
    Route::get('/', 'MainController@index')->name('admin.index');
    Route::get('/file-manager', 'FileManagerController@show')->name('admin.file-manager');
    Route::get('/settings', 'Setting\SettingController@edit')->name('admin.settings');
    Route::post('/settings/update/{id}', 'Setting\SettingController@update')->name('settings.update');
    Route::resource('news', 'News\NewsController');
    Route::resource('pages', 'Page\PageController');
    Route::resource('feedbacks', 'Feedback\FeedbackController');
    Route::post('/pages/drag-and-drop', 'Page\PageController@processDragAndDrop')->name('pages.processDragAndDrop');
});

Auth::routes();

app/Models/News/News.php
<?php

namespace App\Models\News;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    use HasFactory;

    protected $table = 'news';

    protected $fillable = [
        'title',
        'alias',
        'date',
        'anonce',
        'content',
        'image',
        'is_published'
    ];

    protected $casts = [
        'date' => 'datetime',
    ];

}

app/Http/Controllers/Admin/News/NewsController.php
<?php

namespace App\Http\Controllers\Admin\News;

use App\Http\Requests\NewsRequest;
use App\Http\Controllers\Controller;
use App\Models\News\News;

class NewsController extends Controller
{
    public function index()
    {
        return view('admin.news.list', [
            'news' => News::orderBy('created_at','desc')->paginate(10)
        ]);
    }

    public function show($id)
    {
        return view('admin.news.view', [
            'news' => News::find($id)
        ]);
    }

    public function create()
    {
        return view('admin.news.view', [
            'news' => new News()
        ]);
    }

    public function store(NewsRequest $request)
    {
        $validation = $request->validated();
        $news = News::create($validation);

        return redirect('admin/news/' . $news->id)->with('success', 'Новость успешно сохранен!');
    }

    public function update(NewsRequest $request, int $id)
    {
        $validation = $request->validated();
        $news = News::find($id);
        $news->update($validation);

        return redirect('admin/news/' . $news->id)->with('success', 'Новость успешно изменена!');
    }

    public function destroy(int $id)
    {
        $news = News::find($id);
        $news->delete();

        return redirect('admin/news')->with('success', 'Новость удалена');
    }
}

resources/views/admin/news/list.blade.php
@extends('admin.layout.table')

@section('title', 'Новости')

@section('breadcrumbs')
    <li class="breadcrumb-item">Новости</li>
@endsection

@section('create_url')
    {{ route('news.create') }}
@endsection

@section('table')
    <table class="table table-hover table-sm">
        <thead>
        <tr>
            <th>#ID</th>
            <th>Заголовок</th>
            <th>Дата</th>
            <th>Обновлено</th>
            <th>Опубликовано</th>
        </tr>
        </thead>
        <tbody>
            @foreach ($news as $item)
                <tr>
                    <td><a href="{{ route('news.show', [$item->id]) }}">{{ $item->id }}</a></td>
                    <td><a href="{{ route('news.show', [$item->id]) }}">{{ $item->title }}</a></td>
                    <td>{{ date('d.m.Y', strtotime($item->date)) }}</td>
                    <td>{{ date('d.m.Y H:m:s', strtotime($item->updated_at)) }}</td>
                    <td>@if($item->is_published === 1)<i class="far fa-check-square"></i> @endif</td>
                </tr>
            @endforeach
        </tbody>
    </table>
    <div class="d-flex justify-content-center">
        {!! $news->links() !!}
    </div>
@stop

resources/views/admin/news/view.blade.php
@extends('admin.layout.form')

@section('title')
    Редактировать новость
@endsection

@section('breadcrumbs')
    <li class="breadcrumb-item"><a href="{{ route('news.index') }}">Новости</a></li>
    <li class="breadcrumb-item">Редактирование новости</li>
@endsection

@section('form')
    @if (Session::has('success'))
        <div class="alert alert-success" role="alert">
            {{ Session::get('success') }}
        </div>
    @endif
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form role="form"
          action="@if($news->id){{ route('news.update', $news->id) }}@else{{ route('news.store') }}@endif"
          method="POST">
            @if($news->id)
                @method('put')
            @endif
        @csrf
        <div class="card-body">
            <div class="form-group">
                <label for="title">Заголовок</label>
                <input type="text" class="form-control js-transliterate-source" id="title" name="title" placeholder="Заголовок" value="{{ $news->title }}">
            </div>
            <div class="form-group">
                <label for="alias">Алиас</label>
                <a href="#" id="js-transliterate-run" class="float-right" title="Сгенерировать алиас">Сгенерировать</a>
                <input type="text" class="form-control js-transliterate-destination" id="alias" name="alias" placeholder="Алиас" value="{{ $news->alias }}">
            </div>
            <div class="form-group">
                <label for="date">Дата</label>
                <input type="text" class="js-datepicker form-control" id="date" name="date" placeholder="Дата" value="{{ date('d.m.Y', strtotime($news->date)) }}">
            </div>
            <div class="form-group">
                <label for="anonce">Анонс</label>
                <textarea name="anonce" id="anonce" class="ckeditor form-control">{{ $news->anonce }}</textarea>
            </div>
            <div class="form-group">
                <label for="content">Контент</label>
                <textarea name="content" id="content" class="ckeditor form-control">{{ $news->content }}</textarea>
            </div>

            <div class="form-group">
                <label for="image">Картинка</label>
                @if($news->image)
                    <a href="{{$news->image}}" target="_blank" class="thumbnail">
                        <img src="{{$news->image}}" alt="">
                    </a>
                @endif
                <div class="input-group">
                    <input type="text" class="form-control" id="image" name="image" readonly="readonly" value="{{ $news->image }}">
                    <span class="input-group-btn">
                        <button type="button" class="btn btn-primary btn-flat js-open-elfinder" title="Выбрать файл">
                            <i class="far fa-save"></i>
                        </button>
                        <button type="button" class="btn btn-warning btn-flat js-elfinder-file-clear" title="Удалить файл">
                            <i class="far fa-trash-alt"></i>
                        </button>
                    </span>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label required">Опубликовано</label>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="is_published" value="1" @if($news->is_published === 1) checked @endif>
                    <label class="form-check-label">Да</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="is_published" value="0" @if($news->is_published  === 0) checked @endif>
                    <label class="form-check-label">Нет</label>
                </div>
            </div>
        </div>

        <div class="card-footer">
            <button type="submit" class="btn btn-sm btn-success">Сохранить</button>
            @if($news->id)
                <a href="{{ route('news.create') }}" type="button" class="btn btn-sm btn-primary">Создать</a>
            @endif
        </div>
    </form>
    @if($news->id)
        <form class="form" method="POST" action="{{ route('news.destroy', $news->id) }}">
            @csrf
            @method('DELETE')
            <div class="card-body">
                <button type="submit" class="btn btn-sm btn-danger float-right">Удалить</button>
            </div>
        </form>
    @endif
@stop

@section('css')
    @parent
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker3.min.css">
@stop

@section('js')
    @parent

    <script src="{{ asset('js/app/libs/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('js/app/js/ckeditor.js') }}"></script>
    <script src="{{ asset('js/app/js/elfinder-file-type.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/locales/bootstrap-datepicker.ru.min.js"></script>
    <script src="{{ asset('js/app/js/datapicker.js') }}"></script>
    <script src="{{ asset('js/app/js/transliterate.js') }}"></script>
@stop